// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mta.proto

#ifndef PROTOBUF_INCLUDED_mta_2eproto
#define PROTOBUF_INCLUDED_mta_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "crypto-zkp/zkp.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mta_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_mta_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_mta_2eproto();
namespace safeheron {
namespace proto {
class MtaMessageB;
class MtaMessageBDefaultTypeInternal;
extern MtaMessageBDefaultTypeInternal _MtaMessageB_default_instance_;
}  // namespace proto
}  // namespace safeheron
namespace google {
namespace protobuf {
template<> ::safeheron::proto::MtaMessageB* Arena::CreateMaybeMessage<::safeheron::proto::MtaMessageB>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace safeheron {
namespace proto {

// ===================================================================

class MtaMessageB :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.MtaMessageB) */ {
 public:
  MtaMessageB();
  virtual ~MtaMessageB();

  MtaMessageB(const MtaMessageB& from);

  inline MtaMessageB& operator=(const MtaMessageB& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MtaMessageB(MtaMessageB&& from) noexcept
    : MtaMessageB() {
    *this = ::std::move(from);
  }

  inline MtaMessageB& operator=(MtaMessageB&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const MtaMessageB& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MtaMessageB* internal_default_instance() {
    return reinterpret_cast<const MtaMessageB*>(
               &_MtaMessageB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MtaMessageB* other);
  friend void swap(MtaMessageB& a, MtaMessageB& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MtaMessageB* New() const final {
    return CreateMaybeMessage<MtaMessageB>(nullptr);
  }

  MtaMessageB* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MtaMessageB>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MtaMessageB& from);
  void MergeFrom(const MtaMessageB& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MtaMessageB* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string c_b = 1;
  void clear_c_b();
  static const int kCBFieldNumber = 1;
  const ::std::string& c_b() const;
  void set_c_b(const ::std::string& value);
  #if LANG_CXX11
  void set_c_b(::std::string&& value);
  #endif
  void set_c_b(const char* value);
  void set_c_b(const char* value, size_t size);
  ::std::string* mutable_c_b();
  ::std::string* release_c_b();
  void set_allocated_c_b(::std::string* c_b);

  // .safeheron.proto.DLogProof dlog_proof_b = 2;
  bool has_dlog_proof_b() const;
  void clear_dlog_proof_b();
  static const int kDlogProofBFieldNumber = 2;
  const ::safeheron::proto::DLogProof& dlog_proof_b() const;
  ::safeheron::proto::DLogProof* release_dlog_proof_b();
  ::safeheron::proto::DLogProof* mutable_dlog_proof_b();
  void set_allocated_dlog_proof_b(::safeheron::proto::DLogProof* dlog_proof_b);

  // .safeheron.proto.DLogProof dlog_proof_beta_tag = 3;
  bool has_dlog_proof_beta_tag() const;
  void clear_dlog_proof_beta_tag();
  static const int kDlogProofBetaTagFieldNumber = 3;
  const ::safeheron::proto::DLogProof& dlog_proof_beta_tag() const;
  ::safeheron::proto::DLogProof* release_dlog_proof_beta_tag();
  ::safeheron::proto::DLogProof* mutable_dlog_proof_beta_tag();
  void set_allocated_dlog_proof_beta_tag(::safeheron::proto::DLogProof* dlog_proof_beta_tag);

  // @@protoc_insertion_point(class_scope:safeheron.proto.MtaMessageB)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr c_b_;
  ::safeheron::proto::DLogProof* dlog_proof_b_;
  ::safeheron::proto::DLogProof* dlog_proof_beta_tag_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mta_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MtaMessageB

// string c_b = 1;
inline void MtaMessageB::clear_c_b() {
  c_b_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MtaMessageB::c_b() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.MtaMessageB.c_b)
  return c_b_.GetNoArena();
}
inline void MtaMessageB::set_c_b(const ::std::string& value) {
  
  c_b_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.MtaMessageB.c_b)
}
#if LANG_CXX11
inline void MtaMessageB::set_c_b(::std::string&& value) {
  
  c_b_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.MtaMessageB.c_b)
}
#endif
inline void MtaMessageB::set_c_b(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  c_b_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.MtaMessageB.c_b)
}
inline void MtaMessageB::set_c_b(const char* value, size_t size) {
  
  c_b_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.MtaMessageB.c_b)
}
inline ::std::string* MtaMessageB::mutable_c_b() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.MtaMessageB.c_b)
  return c_b_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MtaMessageB::release_c_b() {
  // @@protoc_insertion_point(field_release:safeheron.proto.MtaMessageB.c_b)
  
  return c_b_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MtaMessageB::set_allocated_c_b(::std::string* c_b) {
  if (c_b != nullptr) {
    
  } else {
    
  }
  c_b_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), c_b);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.MtaMessageB.c_b)
}

// .safeheron.proto.DLogProof dlog_proof_b = 2;
inline bool MtaMessageB::has_dlog_proof_b() const {
  return this != internal_default_instance() && dlog_proof_b_ != nullptr;
}
inline const ::safeheron::proto::DLogProof& MtaMessageB::dlog_proof_b() const {
  const ::safeheron::proto::DLogProof* p = dlog_proof_b_;
  // @@protoc_insertion_point(field_get:safeheron.proto.MtaMessageB.dlog_proof_b)
  return p != nullptr ? *p : *reinterpret_cast<const ::safeheron::proto::DLogProof*>(
      &::safeheron::proto::_DLogProof_default_instance_);
}
inline ::safeheron::proto::DLogProof* MtaMessageB::release_dlog_proof_b() {
  // @@protoc_insertion_point(field_release:safeheron.proto.MtaMessageB.dlog_proof_b)
  
  ::safeheron::proto::DLogProof* temp = dlog_proof_b_;
  dlog_proof_b_ = nullptr;
  return temp;
}
inline ::safeheron::proto::DLogProof* MtaMessageB::mutable_dlog_proof_b() {
  
  if (dlog_proof_b_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::DLogProof>(GetArenaNoVirtual());
    dlog_proof_b_ = p;
  }
  // @@protoc_insertion_point(field_mutable:safeheron.proto.MtaMessageB.dlog_proof_b)
  return dlog_proof_b_;
}
inline void MtaMessageB::set_allocated_dlog_proof_b(::safeheron::proto::DLogProof* dlog_proof_b) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(dlog_proof_b_);
  }
  if (dlog_proof_b) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      dlog_proof_b = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, dlog_proof_b, submessage_arena);
    }
    
  } else {
    
  }
  dlog_proof_b_ = dlog_proof_b;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.MtaMessageB.dlog_proof_b)
}

// .safeheron.proto.DLogProof dlog_proof_beta_tag = 3;
inline bool MtaMessageB::has_dlog_proof_beta_tag() const {
  return this != internal_default_instance() && dlog_proof_beta_tag_ != nullptr;
}
inline const ::safeheron::proto::DLogProof& MtaMessageB::dlog_proof_beta_tag() const {
  const ::safeheron::proto::DLogProof* p = dlog_proof_beta_tag_;
  // @@protoc_insertion_point(field_get:safeheron.proto.MtaMessageB.dlog_proof_beta_tag)
  return p != nullptr ? *p : *reinterpret_cast<const ::safeheron::proto::DLogProof*>(
      &::safeheron::proto::_DLogProof_default_instance_);
}
inline ::safeheron::proto::DLogProof* MtaMessageB::release_dlog_proof_beta_tag() {
  // @@protoc_insertion_point(field_release:safeheron.proto.MtaMessageB.dlog_proof_beta_tag)
  
  ::safeheron::proto::DLogProof* temp = dlog_proof_beta_tag_;
  dlog_proof_beta_tag_ = nullptr;
  return temp;
}
inline ::safeheron::proto::DLogProof* MtaMessageB::mutable_dlog_proof_beta_tag() {
  
  if (dlog_proof_beta_tag_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::DLogProof>(GetArenaNoVirtual());
    dlog_proof_beta_tag_ = p;
  }
  // @@protoc_insertion_point(field_mutable:safeheron.proto.MtaMessageB.dlog_proof_beta_tag)
  return dlog_proof_beta_tag_;
}
inline void MtaMessageB::set_allocated_dlog_proof_beta_tag(::safeheron::proto::DLogProof* dlog_proof_beta_tag) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(dlog_proof_beta_tag_);
  }
  if (dlog_proof_beta_tag) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      dlog_proof_beta_tag = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, dlog_proof_beta_tag, submessage_arena);
    }
    
  } else {
    
  }
  dlog_proof_beta_tag_ = dlog_proof_beta_tag;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.MtaMessageB.dlog_proof_beta_tag)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace safeheron

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_mta_2eproto
